# MobHostility v1.0
#
# World types where mob targeting is modified.
# Valid options:
#   - overworld
#   - nether
#   - end
#   - all
#   - none
#
# A world name must be specified if "none" is used here
# Specify options with [] brackets separated by commas.
#
worldtypes: [ nether ]

#
# Names of the worlds where mob targeting is modified (Case-sensitive!)
#
worldnames:

#
# Names of mobs whose targeting will be modified for the listed
# armor and items. To have a certain item affect all mobs, use the
# "all" mob name. Place protective items in the "passive" category
# and dangerous items in the "hostile" category
#
# Format:
# mobitems:
#   mobname:
#     hostile:
#       helmets:
#       chestplates:
#       leggings:
#       boots:
#       items:
#     passive:
#       helmets:
#       chestplates:
#       leggings:
#       boots:
#       items:
#
# Valid mob names:
#   - zombie
#   - skeleton
#   - spider
#   - cave_spider
#   - creeper
#   - slime
#   - silverfish
#   - enderman
#   - ender_dragon
#   - pig_zombie
#   - blaze
#   - ghast
#   - magma_cube
#   - giant
#   - all
#
# Items must be a list of Item IDs, not names! Items must be in 
# [] brackets separated by commas.
#
mobitems:
  all:
    hostile:
      helmets: [ ]
      chestplates: [ ]
      leggings: [ ]
      boots: [ ]
      items: [ ]
    passive:
      helmets: [ ]
      chestplates: [ ]
      leggings: [ ]
      boots: [ ]
      items: [ ]
#
# Block radius from the player to check for mobs
# hostilecheck - for making mobs hostile
# passivecheck - for making mobs forget the player
#
hostileradius: 64
passiveradius: 64
#
# Time in seconds in between player inventory/armor checks
# Minimum: 1 (20 server ticks)
#
time: 5